version: "3"

networks:
  event-driven-system:
    driver: bridge

services:
  inventory_mongo_db:
    image: mongo:5.0.10
    container_name: inventory_mongo_db
    hostname: inventory_mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - ./init-mongodb/data:/tmp/data
      - ./data/mongo-volume:/data/db
    networks:
        - event-driven-system

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8099:8081
    depends_on:
      - inventory_mongo_db
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: inventory_mongo_db
    links:
      - inventory_mongo_db  
    networks:
        - event-driven-system
